# Generated by Django 3.2.12 on 2022-03-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user_comments',
        ),
        migrations.AddField(
            model_name='food',
            name='user_comments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='all_food_items', to='accounts.user'),
        ),
    ]
