# Generated by Django 4.0.2 on 2022-03-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user_comments',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_comment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.food')),
            ],
        ),
    ]
