# Generated by Django 4.0.2 on 2022-03-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_food_user_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='food_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.food'),
        ),
    ]
