# Generated by Django 3.2.12 on 2022-03-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220320_2300'),
        ('accounts', '0003_remove_food_user_comments_comment'),
    ]

    operations = [
    ]
