# Generated by Django 4.0.2 on 2022-04-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uploaded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded', to='accounts.user'),
        ),
    ]
