# Generated by Django 4.0.2 on 2022-04-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_comment_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uploaded_by',
        ),
    ]
