# Generated by Django 4.0.2 on 2022-03-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_comment_food_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='food_comment',
            new_name='post',
        ),
    ]
